function planoDinJarrattf34orden
%Dibuja el plano dinámico del método de JARRATT para la función f_3(x)

li=-3;ls=3;%Definimos los límites para los intervalos
N=500; maxiter=80; tol=1e-6;
x=linspace(li,ls,N); y=x;
[X,Y]=meshgrid(x,y);
z=X+1i*Y;

%Raíces
raices=[0.57871364351972412878877297753342];

%Operador de punto fijo
R=@(z)((z*(6*z^3*cos(z)^3 - ...
     z^2*cos(z)^2*(18*z*...
         cos((z*(3 + 3*z*cos(z) - 2*log(2*z) - 2*sin(z)))/(3 + ...
             3*z*cos(z))) + log(2*z) + sin(z)) + ...
         z*...
      cos((z*(3 + 3*z*cos(z) - 2*log(2*z) - 2*sin(z)))/(3 + ...
          3*z*cos(z)))*(-19 + cos(2*z) + 15*log(2*z) - ...
        2*log(2*z)^2 + (15 - 4*log(2*z))*sin(z)) + ...
         z*...
      cos(z)*(-19 + cos(2*z) + log(2*z) - 2*log(2*z)^2 + sin(z) + ...
        3*z*cos((z*(3 + 3*z*cos(z) - 2*log(2*z) - 2*sin(z)))/(3 + ...
             3*z*cos(z)))*(-12 + 5*log(2*z) + 5*sin(z))) - ...
         2*(6 - log(2*z) + ...
        log(2*z)^2 + (-1 + log(4) + 2*log(z))*sin(z) + sin(z)^2 + ...
        z*log(2*z)*sin(2*z))))/...
   (2*(1 + z*cos(z))*(3*z^2*cos(z)^2 - 2*(3 + log(2*z) + sin(z)) + ...
     3*z*cos((z*(3 + 3*z*cos(z) - 2*log(2*z) - 2*sin(z)))/(3 + ...
          3*z*cos(z)))*(-3 + log(4) + 2*log(z) + 2*sin(z)) - ...
         z*...
      cos(z)*(3 + ...
        9*z*cos((z*(3 + 3*z*cos(z) - 2*log(2*z) - 2*sin(z)))/(3 + ...
             3*z*cos(z))) + log(4) + 2*log(z) + 2*sin(z)))));
for j=1:N
    for k=1:N
        z0=z(j,k);
        z0=R(z0); iter=1; dif=tol+1;
        while and(iter<maxiter,dif>tol)
            z0=R(z0);
            dif1=abs(z0-raices(1)); %dif2=abs(z0-raices(2));
            %dif3=abs(z0-raices(3));
            dif=dif1;
            iter=iter+1;
        end
        y(j,k)=z0;
        IT(j,k)=iter;
    end
end
p=polyfit([min(IT(:)) max(IT(:))],[1 .25],1);
cIT=polyval(p,IT);

Z1=abs(y-raices(1))<tol;
%Z2=abs(y-raices(2))<tol;
%Z3=abs(y-raices(3))<tol;

I(:,:,1)=cIT.*(237/255*Z1);
I(:,:,2)=cIT.*(85/255*Z1);
I(:,:,3)=cIT.*(70/225*Z1);

figure, imshow(double(I),'XData',[li ls],'YData',[li ls]), axis on, axis xy
hold on
plot(real(raices),imag(raices),'w*'), xlabel('Real(z)'),...
    ylabel('Imag(z)'), grid
end

